Include a method "GetAllRecords". Returns all records in hosts file.
AMVSoftware/Cake.Hosts pull request #14
Opened 2020-02-01 04:45 UTC by tiago-aguiar-moreira

2020-02-03 10:31 UTC, trailmax commented
@tiago-aguiar-moreira Thanks for the PR, I was planning to get this reviewed/merged over the weekend, but life happened with some urgent house work needed to be done.
I'm hoping I'll have a chance to get this reviewed during the week. Please bear with me.

2020-02-04 01:44 UTC, tiago-aguiar-moreira commented
@trailmax , no problem!

2020-02-06 01:57 UTC, trailmax requested changes
The work is good, just some corrections needed to get code in line with the rest of the codebase

2020-02-06 01:57 UTC, trailmax commented on src/Cake.Hosts/HostsFile.cs
> +    public class HostsFile
I'd rename that to be `HostsRecord` as this really represents a line in hosts file, not the entire hosts file.

2020-02-06 01:57 UTC, trailmax commented on src/Cake.Hosts/HostsFileUtil.cs
> +    public class HostsFileUtil
Please make this class and all it's members `internal` as this should not be exposed for external use

2020-02-06 01:57 UTC, trailmax commented on src/Cake.Hosts/HostsFileUtil.cs
> +        static public bool IsLineAHostFile(string line)
More appropriate name is `IsLineAHostsRecord`

2020-02-06 01:57 UTC, trailmax commented on src/Cake.Hosts/HostsFileUtil.cs
> +                throw new InvalidDataException();
I'm not sure about this one. I'd rather not throw any exceptions if format of the string does not match, just skip that line with a possible log entry. 

Also, I feel there is no need to go 2 levels of methods that should be internal anyway. i.e. `TryGetHostsFileEntry` is not used anywhere outside of `GetHostsFile` and it does not add to the readability.

2020-02-06 01:57 UTC, trailmax commented on src/Cake.Hosts/HostsFileUtil.cs
> +        static public bool IsLineAHostFile(string line)
Also, can we use the regex to do the matching, rather than just check that it does not start with `#`?

2020-02-06 01:57 UTC, trailmax commented on src/Cake.Hosts/CakeHostsAliases.cs
> +            if (result.Any())
I'd rather move all the logging into internal `CakeHosts` class that contains all the implementation to preserve the Cake convention that `*Alias` class is only a thin wrapper around the `*Impl` class.

2020-02-06 01:57 UTC, trailmax commented on src/Cake.Hosts/CakeHostsAliases.cs
> +                    context.Log.Write(Verbosity.Normal, LogLevel.Information, $"IP {item.Ip} with Hostname {item.Hostname}");
I feel that should rather be a `Debug` level log output. 
However for `Normal` log output I'd say `$"Hosts file contains {count} records"`

2020-02-06 01:57 UTC, trailmax commented on src/Cake.Hosts.Tests/CakeHostsTests.cs
> +        public void GetAllRecords_Find_Records()
There should be an assertive test, confirming that returned values indeed are contained in the file. 
One of the lines in the file should be an invalid record, another line should be a comment - those should be ignored
And at least 2 records in file and check that those are returned in the list

2023-08-10 00:01 UTC, closed without merging